package resolver

import (
	"github.com/YuanziX/files-backend/internal/config"
	"github.com/YuanziX/files-backend/internal/database/postgres"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

// This file will not be regenerated automatically.
//
// It serves as dependency injection for your app, add any dependencies you require here.
// IMPORTANT: This file should ONLY contain the Resolver struct definition.
// All other resolver methods should be in the files generated by gqlgen.
type Resolver struct {
	DB              postgres.Querier
	Cfg             *config.Config
	S3Client        *s3.Client
	S3PresignClient *s3.PresignClient

	S3BucketName string
}
