// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	PhysicalFileID pgtype.UUID        `json:"physical_file_id"`
	FolderID       pgtype.UUID        `json:"folder_id"`
	Filename       string             `json:"filename"`
	Tags           []string           `json:"tags"`
	UploadDate     pgtype.Timestamptz `json:"upload_date"`
}

type Folder struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PhysicalFile struct {
	ID             pgtype.UUID        `json:"id"`
	ContentHash    string             `json:"content_hash"`
	MimeType       string             `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	StoragePath    string             `json:"storage_path"`
	ReferenceCount int32              `json:"reference_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Share struct {
	ID               pgtype.UUID        `json:"id"`
	FileID           pgtype.UUID        `json:"file_id"`
	FolderID         pgtype.UUID        `json:"folder_id"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	SharedWithUserID pgtype.UUID        `json:"shared_with_user_id"`
	ShareType        string             `json:"share_type"`
	PublicToken      pgtype.Text        `json:"public_token"`
	DownloadCount    int32              `json:"download_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	Role              string             `json:"role"`
	StorageQuotaBytes int64              `json:"storage_quota_bytes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
