// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFileReference(ctx context.Context, arg CreateFileReferenceParams) (File, error)
	CreatePhysicalFile(ctx context.Context, arg CreatePhysicalFileParams) (PhysicalFile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPhysicalFileByHash(ctx context.Context, contentHash string) (PhysicalFile, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListFilesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]File, error)
}

var _ Querier = (*Queries)(nil)
