// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/YuanziX/files-backend/internal/database/postgres"
)

type AuthResponse struct {
	User  *postgres.User `json:"user"`
	Token string         `json:"token"`
}

type ConfirmUploadInput struct {
	Filename string `json:"filename"`
	Hash     string `json:"hash"`
	Size     int32  `json:"size"`
	MimeType string `json:"mimeType"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PreSignedURL struct {
	Filename  string `json:"filename"`
	Hash      string `json:"hash"`
	UploadURL string `json:"uploadURL"`
}

type PreUploadCheckResponse struct {
	CompletedFiles []*postgres.File `json:"completedFiles"`
	NewFiles       []*PreSignedURL  `json:"newFiles"`
}

type PreUploadFileInput struct {
	Filename string `json:"filename"`
	Hash     string `json:"hash"`
}

type Query struct {
}

type RegisterUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
